package com.hfad.mycosmetologist.ui.theme

import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFFB39DDB)
val onPrimaryLight = Color(0xFF2A1B3D)

val primaryContainerLight = Color(0xFFD1C4E9)
val onPrimaryContainerLight = Color(0xFF2A1B3D)


// SECONDARY (mint)
val secondaryLight = Color(0xFF7FD3C5)
val onSecondaryLight = Color(0xFF00332B)

val secondaryContainerLight = Color(0xFFCFF5E7)
val onSecondaryContainerLight = Color(0xFF00332B)
val tertiaryLight = Color(0xFF82524E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDAD7)
val onTertiaryContainerLight = Color(0xFF663B37)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF7F6FB)
val surfaceLight = Color(0xFFFFFFFF)

val surfaceContainerLight = Color(0xFFF1EFFA)
val surfaceContainerHighLight = Color(0xFFEAE7F7)
val surfaceContainerHighestLight = Color(0xFFE3E0F3)


// OUTLINE (мягкий mint-серый)
val outlineLight = Color(0xFFD6EAE5)
val outlineVariantLight = Color(0xFFE3F1ED)


// INVERSE PRIMARY (для dark overlays)
val inversePrimaryLight = Color(0xFF8E7CC3)
val onBackgroundLight = Color(0xFF1F1A1F)
val onSurfaceLight = Color(0xFF1F1A1F)
val surfaceVariantLight = Color(0xFFEBDFE9)
val onSurfaceVariantLight = Color(0xFF4C444C)

val inverseSurfaceLight = Color(0xFF342F34)
val inverseOnSurfaceLight = Color(0xFFF8EEF5)
val surfaceDimLight = Color(0xFFDCE5E1)
val surfaceBrightLight = Color(0xFFF3F6F4)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEEF4F1)

val scrimLight = Color(0xFF000000)

val primaryLightMediumContrast = Color(0xFF4C2758)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF885E92)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF003E35)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF207A6B)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF532B28)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF92605C)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF7FB)
val onBackgroundLightMediumContrast = Color(0xFF1F1A1F)
val surfaceLightMediumContrast = Color(0xFFFFF7FB)
val onSurfaceLightMediumContrast = Color(0xFF141015)
val surfaceVariantLightMediumContrast = Color(0xFFEBDFE9)
val onSurfaceVariantLightMediumContrast = Color(0xFF3B343C)
val outlineLightMediumContrast = Color(0xFF585058)
val outlineVariantLightMediumContrast = Color(0xFF736A73)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF342F34)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF8EEF5)
val inversePrimaryLightMediumContrast = Color(0xFFE7B6F1)
val surfaceDimLightMediumContrast = Color(0xFFCDC4CB)
val surfaceBrightLightMediumContrast = Color(0xFFFFF7FB)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFBF1F8)
val surfaceContainerLightMediumContrast = Color(0xFFF0E5ED)
val surfaceContainerHighLightMediumContrast = Color(0xFFE4DAE1)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD9CFD6)

val primaryLightHighContrast = Color(0xFF411D4D)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF613A6C)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF00332B)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF005348)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF47211E)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF693D3A)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF7FB)
val onBackgroundLightHighContrast = Color(0xFF1F1A1F)
val surfaceLightHighContrast = Color(0xFFFFF7FB)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFEBDFE9)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF312A31)
val outlineVariantLightHighContrast = Color(0xFF4F474F)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF342F34)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFE7B6F1)
val surfaceDimLightHighContrast = Color(0xFFBFB6BD)
val surfaceBrightLightHighContrast = Color(0xFFFFF7FB)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF8EEF5)
val surfaceContainerLightHighContrast = Color(0xFFEAE0E7)
val surfaceContainerHighLightHighContrast = Color(0xFFDBD2D9)
val surfaceContainerHighestLightHighContrast = Color(0xFFCDC4CB)

val primaryDark = Color(0xFFE7B6F1)
val onPrimaryDark = Color(0xFF462151)
val primaryContainerDark = Color(0xFF5E3869)
val onPrimaryContainerDark = Color(0xFFFAD7FF)
val secondaryDark = Color(0xFF83D5C4)
val onSecondaryDark = Color(0xFF003730)
val secondaryContainerDark = Color(0xFF005046)
val onSecondaryContainerDark = Color(0xFF9FF2E0)
val tertiaryDark = Color(0xFFF5B7B2)
val onTertiaryDark = Color(0xFF4C2522)
val tertiaryContainerDark = Color(0xFF663B37)
val onTertiaryContainerDark = Color(0xFFFFDAD7)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF161217)
val onBackgroundDark = Color(0xFFEAE0E7)
val surfaceDark = Color(0xFF161217)
val onSurfaceDark = Color(0xFFEAE0E7)
val surfaceVariantDark = Color(0xFF4C444C)
val onSurfaceVariantDark = Color(0xFFCFC3CD)
val outlineDark = Color(0xFF988E97)
val outlineVariantDark = Color(0xFF4C444C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEAE0E7)
val inverseOnSurfaceDark = Color(0xFF342F34)
val inversePrimaryDark = Color(0xFF784F83)
val surfaceDimDark = Color(0xFF161217)
val surfaceBrightDark = Color(0xFF3D373D)
val surfaceContainerLowestDark = Color(0xFF110D12)
val surfaceContainerLowDark = Color(0xFF1F1A1F)
val surfaceContainerDark = Color(0xFF231E23)
val surfaceContainerHighDark = Color(0xFF2E282E)
val surfaceContainerHighestDark = Color(0xFF393339)

val primaryDarkMediumContrast = Color(0xFFF8CFFF)
val onPrimaryDarkMediumContrast = Color(0xFF3A1646)
val primaryContainerDarkMediumContrast = Color(0xFFAE81B8)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFF99ECDA)
val onSecondaryDarkMediumContrast = Color(0xFF002C25)
val secondaryContainerDarkMediumContrast = Color(0xFF4C9E8F)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFD2CE)
val onTertiaryDarkMediumContrast = Color(0xFF3F1B18)
val tertiaryContainerDarkMediumContrast = Color(0xFFBA837E)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF161217)
val onBackgroundDarkMediumContrast = Color(0xFFEAE0E7)
val surfaceDarkMediumContrast = Color(0xFF161217)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF4C444C)
val onSurfaceVariantDarkMediumContrast = Color(0xFFE5D9E3)
val outlineDarkMediumContrast = Color(0xFFBAAFB8)
val outlineVariantDarkMediumContrast = Color(0xFF978D97)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFEAE0E7)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2E282E)
val inversePrimaryDarkMediumContrast = Color(0xFF60396B)
val surfaceDimDarkMediumContrast = Color(0xFF161217)
val surfaceBrightDarkMediumContrast = Color(0xFF494348)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0A060A)
val surfaceContainerLowDarkMediumContrast = Color(0xFF211C21)
val surfaceContainerDarkMediumContrast = Color(0xFF2B262C)
val surfaceContainerHighDarkMediumContrast = Color(0xFF363136)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF423C42)

val primaryDarkHighContrast = Color(0xFFFFE9FF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFE3B2ED)
val onPrimaryContainerDarkHighContrast = Color(0xFF1A0024)
val secondaryDarkHighContrast = Color(0xFFB1FFEE)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF7FD2C0)
val onSecondaryContainerDarkHighContrast = Color(0xFF000E0B)
val tertiaryDarkHighContrast = Color(0xFFFFECEA)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFF1B4AE)
val onTertiaryContainerDarkHighContrast = Color(0xFF1E0303)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF161217)
val onBackgroundDarkHighContrast = Color(0xFFEAE0E7)
val surfaceDarkHighContrast = Color(0xFF161217)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4C444C)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF9ECF7)
val outlineVariantDarkHighContrast = Color(0xFFCBBFC9)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFEAE0E7)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF60396B)
val surfaceDimDarkHighContrast = Color(0xFF161217)
val surfaceBrightDarkHighContrast = Color(0xFF554E54)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF231E23)
val surfaceContainerDarkHighContrast = Color(0xFF342F34)
val surfaceContainerHighDarkHighContrast = Color(0xFF3F3A3F)
val surfaceContainerHighestDarkHighContrast = Color(0xFF4B454B)




